version: '3.8'

services:
  gempp-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gempp-cli
    volumes:
      - ./data:/data
    working_dir: /data
    command: ["--help"]
